apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc-nodeappexample-0
spec:
  storageClassName: rook-ceph-block
  dataSource:
    name: snapshot-pvc-nodeappexample-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
