apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: snapshot-pvc-nodeappexample-0
spec:
  snapshotClassName: csi-rbdplugin-snapclass 
  source:
    name: data-nodetodoexample-nodeappexample-0
    kind: PersistentVolumeClaim


